CREATE TABLE account (
    account_number VARCHAR(50) NOT NULL PRIMARY KEY,
    balance DECIMAL(19, 4) NOT NULL DEFAULT 0.0000,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE journal_entry (
    id VARCHAR(100) NOT NULL PRIMARY KEY,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ledger_movement (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    journal_entry_id VARCHAR(100) NOT NULL,
    account_number VARCHAR(50) NOT NULL,
    type VARCHAR(10) NOT NULL, -- 'DEBIT' or 'CREDIT'
    amount DECIMAL(19, 4) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_movement_journal FOREIGN KEY (journal_entry_id) REFERENCES journal_entry(id),
    CONSTRAINT fk_movement_account FOREIGN KEY (account_number) REFERENCES account(account_number)
);

CREATE TABLE audit_checkpoint (
    id VARCHAR(50) NOT NULL PRIMARY KEY,
    last_processed_id BIGINT NOT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
