-- F02 — immutable ledger
-- Two tables: journal_entry (PENDING/VERIFIED/FAILED status + metadata) and
-- ledger_movement (debit/credit legs with monotonic BIGINT IDENTITY ids).
-- All movements are append-only; the only mutable column is
-- journal_entry.verification_status, transitioned by the domain aggregate.

CREATE TABLE journal_entry (
    id                  UUID                       NOT NULL PRIMARY KEY,
    description         VARCHAR(255)               NOT NULL,
    entry_timestamp     TIMESTAMP WITH TIME ZONE   NOT NULL,
    verification_status VARCHAR(16)                NOT NULL,
    CONSTRAINT verification_status_valid
        CHECK (verification_status IN ('PENDING', 'VERIFIED', 'FAILED'))
);

CREATE TABLE ledger_movement (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    journal_entry_id UUID            NOT NULL,
    movement_order   INTEGER         NOT NULL,
    account_id       UUID            NOT NULL,
    amount           NUMERIC(19, 2)  NOT NULL,
    movement_type    VARCHAR(8)      NOT NULL,
    CONSTRAINT fk_ledger_movement_journal
        FOREIGN KEY (journal_entry_id) REFERENCES journal_entry(id),
    CONSTRAINT amount_positive CHECK (amount > 0),
    CONSTRAINT movement_type_valid
        CHECK (movement_type IN ('DEBIT', 'CREDIT'))
);

CREATE INDEX idx_ledger_movement_account_id ON ledger_movement(account_id);
CREATE INDEX idx_ledger_movement_journal_id ON ledger_movement(journal_entry_id);
CREATE INDEX idx_journal_entry_status       ON journal_entry(verification_status);
