CREATE OR REPLACE VIEW transaction_view AS
SELECT amount, type, TIMESTAMP, JOURNAL_ENTRY_ID, DESCRIPTION
FROM ledger_transactions
         JOIN JOURNAL_ENTRIES ON JOURNAL_ENTRY_ID = JOURNAL_ENTRIES.ID;
